"""
Django settings for ImobCalc project.

Generated by 'django-admin startproject' using Django 5.2.8.
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-l+!&ap-ea#+k04nfu=blp9j+@22be)qvo8=_dk@)onb()ilci7'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.humanize', # Adicionado para formatação de moeda no template
    
    # Seus Apps Locais
    'simulacao', # Seu App
    
    # Apps Allauth
    'django.contrib.sites', 
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.google',  # OAuth Google
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'allauth.account.middleware.AccountMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    # Middlewares customizados para gerenciamento de sessão
    'simulacao.middleware.SessionActivityMiddleware',
    'simulacao.middleware.SessionSecurityMiddleware',
]

ROOT_URLCONF = 'ImobCalc.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'simulacao/templates', BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'ImobCalc.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization e Configuração PT-BR
# ----------------------------------------------------------------------

LANGUAGE_CODE = 'pt-br' 

TIME_ZONE = 'UTC'

USE_I18N = True

# USE_L10N está depreciado no Django 4.0+. Use USE_I18N e configurações específicas de formato.
# USE_L10N = True 

USE_TZ = True

# Configurações Específicas para Formato de Número Brasileiro (PT-BR)
DECIMAL_SEPARATOR = ','    # Vírgula para decimal
THOUSAND_SEPARATOR = '.'   # Ponto para milhar


# Static files (CSS, JavaScript, Images)
# ----------------------------------------------------------------------

STATIC_URL = 'static/'
STATICFILES_DIRS = [
    BASE_DIR / "static",
]

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# Configurações Allauth (Autenticação) - CORRIGIDAS
# ----------------------------------------------------------------------

# 1. SITE_ID é obrigatório para o allauth
SITE_ID = 1

# 2. Backends de Autenticação
AUTHENTICATION_BACKENDS = (
    # Necessário para logar com username e password (admin)
    'django.contrib.auth.backends.ModelBackend',
    # Allauth específico (para redes sociais e e-mail)
    'allauth.account.auth_backends.AuthenticationBackend',
)

# Redireciona para a raiz após o login
LOGIN_REDIRECT_URL = '/dashboard/' 
# Redireciona para a raiz após o logout
ACCOUNT_LOGOUT_REDIRECT_URL = '/' 

# CAMPOS DE SIGNUP: Usamos 'email*' para satisfazer ACCOUNT_EMAIL_VERIFICATION = "mandatory"
# O campo de senha é gerenciado internamente pelo allauth.
ACCOUNT_SIGNUP_FIELDS = ['username', 'email*'] 

# MÉTODOS DE LOGIN: Permite login usando tanto 'username' quanto 'email'
ACCOUNT_LOGIN_METHODS = ["username", "email"] 

# Define se a verificação de e-mail é obrigatória
ACCOUNT_EMAIL_VERIFICATION = "optional"  # Reativado para maior segurança

# As configurações depreciadas (ACCOUNT_AUTHENTICATION_METHOD, ACCOUNT_EMAIL_REQUIRED, ACCOUNT_USERNAME_REQUIRED) 
# foram removidas/são deduzidas das linhas acima para evitar warnings.

# Configurações de Autenticação Customizada
# ----------------------------------------------------------------------

# Define o modelo de usuário customizado
AUTH_USER_MODEL = 'simulacao.CustomUser'

# URL de login
LOGIN_URL = '/accounts/login/'

# Configurações de Email (para desenvolvimento - console backend)
EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'

# Configurações de Mídia (para uploads de avatar, etc.)
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Configurações de Sessão
SESSION_EXPIRE_AT_BROWSER_CLOSE = False
SESSION_COOKIE_AGE = 1209600  # 14 dias em segundos
SESSION_SAVE_EVERY_REQUEST = True  # Atualiza tempo de expiração a cada requisição
SESSION_COOKIE_NAME = 'imobcalc_sessionid'
SESSION_COOKIE_SECURE = False  # True em produção com HTTPS
SESSION_COOKIE_HTTPONLY = True  # Previne acesso via JavaScript
SESSION_COOKIE_SAMESITE = 'Lax'  # Proteção CSRF
SESSION_ENGINE = 'django.contrib.sessions.backends.db'
SESSION_COOKIE_AGE_REMEMBER_ME = 2592000  # 30 dias para "Manter-me conectado"


# Configurações de OAuth Social (Google, Apple, etc.)
# ----------------------------------------------------------------------
SOCIALACCOUNT_PROVIDERS = {
        'google': {
                    'SCOPE': ['profile', 'email'],
                            'AUTH_PARAMS': {'access_type': 'online'},
                                    'APP': {
                                                    'client_id': 'SEU_GOOGLE_CLIENT_ID',  # Substituir com credenciais reais
                                                                'secret': 'SEU_GOOGLE_CLIENT_SECRET',  # Substituir com credenciais reais
                                                                            'key': ''
                                    }
        }
}

SOCIALACCOUNT_AUTO_SIGNUP = True  # Cria conta automaticamente no primeiro login social
SOCIALACCOUNT_EMAIL_VERIFICATION = 'none'  # Email já verificado pelo provider

# Habilitar login automático após o cadastro
ACCOUNT_LOGIN_ON_EMAIL_CONFIRMATION = False