# Generated by Django 5.2.8 on 2025-11-23 01:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CenarioComparativo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_imovel', models.DecimalField(decimal_places=2, max_digits=15)),
                ('entrada', models.DecimalField(decimal_places=2, max_digits=15)),
                ('prazo_anos', models.IntegerField()),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ResultadoComparacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metodo', models.CharField(choices=[('PRICE', 'Tabela Price'), ('SAC', 'Tabela SAC'), ('CONS', 'Consórcio'), ('RENDA', 'Aluguel + Investimento')], max_length=5)),
                ('parcela_inicial', models.DecimalField(decimal_places=2, max_digits=15)),
                ('total_pago', models.DecimalField(decimal_places=2, max_digits=15)),
                ('total_juros_ou_custo', models.DecimalField(decimal_places=2, max_digits=15)),
                ('taxa_juros_anual', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('cenario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='simulacao.cenariocomparativo')),
            ],
        ),
        migrations.CreateModel(
            name='Simulacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_imovel', models.DecimalField(decimal_places=2, max_digits=15)),
                ('entrada', models.DecimalField(decimal_places=2, max_digits=15)),
                ('taxa_anual', models.DecimalField(decimal_places=2, max_digits=5)),
                ('prazo_meses', models.IntegerField()),
                ('parcela_fixa', models.DecimalField(decimal_places=2, max_digits=15)),
                ('total_juros', models.DecimalField(decimal_places=2, max_digits=15)),
                ('data_simulacao', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='simulacao.usuario')),
            ],
        ),
        migrations.AddField(
            model_name='cenariocomparativo',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='simulacao.usuario'),
        ),
    ]
