# Generated by Django 6.0.1 on 2026-02-01 19:39

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CenarioComparativo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_imovel', models.DecimalField(decimal_places=2, max_digits=15)),
                ('entrada', models.DecimalField(decimal_places=2, max_digits=15)),
                ('prazo_anos', models.IntegerField()),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('telefone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefone')),
                ('data_nascimento', models.DateField(blank=True, null=True, verbose_name='Data de Nascimento')),
                ('tipo_conta', models.CharField(choices=[('FREE', 'Gratuita'), ('PREMIUM', 'Premium')], default='FREE', max_length=10, verbose_name='Tipo de Conta')),
                ('premium_expira_em', models.DateTimeField(blank=True, null=True, verbose_name='Premium Expira em')),
                ('aceitou_termos', models.BooleanField(default=False, verbose_name='Aceitou Termos de Uso')),
                ('aceitou_privacidade', models.BooleanField(default=False, verbose_name='Aceitou Política de Privacidade')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Usuário',
                'verbose_name_plural': 'Usuários',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='ResultadoComparacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metodo', models.CharField(choices=[('PRICE', 'Tabela Price'), ('SAC', 'Tabela SAC'), ('CONS', 'Consórcio'), ('RENDA', 'Aluguel + Investimento')], max_length=5)),
                ('parcela_inicial', models.DecimalField(decimal_places=2, max_digits=15)),
                ('total_pago', models.DecimalField(decimal_places=2, max_digits=15)),
                ('total_juros_ou_custo', models.DecimalField(decimal_places=2, max_digits=15)),
                ('taxa_juros_anual', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('cenario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='simulacao.cenariocomparativo')),
            ],
        ),
        migrations.CreateModel(
            name='SavedSimulation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(help_text="Ex: 'Apartamento Centro - 300k'", max_length=200, verbose_name='Título da Simulação')),
                ('dados_wizard', models.JSONField(help_text='Todos os dados coletados nas 5 etapas do wizard', verbose_name='Dados do Wizard')),
                ('resultados', models.JSONField(help_text='Resultados calculados para todos os cenários', verbose_name='Resultados da Simulação')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('is_favorito', models.BooleanField(default=False, verbose_name='Favorito')),
                ('notas', models.TextField(blank=True, help_text='Anotações pessoais sobre esta simulação', null=True, verbose_name='Notas')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='simulacoes_salvas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Simulação Salva',
                'verbose_name_plural': 'Simulações Salvas',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='SimulationShare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=64, unique=True, verbose_name='Token de Compartilhamento')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('expira_em', models.DateTimeField(blank=True, null=True, verbose_name='Expira em')),
                ('visualizacoes', models.IntegerField(default=0, verbose_name='Visualizações')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('simulacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compartilhamentos', to='simulacao.savedsimulation')),
            ],
            options={
                'verbose_name': 'Compartilhamento de Simulação',
                'verbose_name_plural': 'Compartilhamentos de Simulações',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpf', models.CharField(blank=True, max_length=14, null=True, verbose_name='CPF')),
                ('renda_mensal', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Renda Mensal')),
                ('receber_notificacoes', models.BooleanField(default=True, verbose_name='Receber Notificações')),
                ('receber_emails_marketing', models.BooleanField(default=False, verbose_name='Receber E-mails de Marketing')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/', verbose_name='Avatar')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Perfil de Usuário',
                'verbose_name_plural': 'Perfis de Usuários',
            },
        ),
        migrations.CreateModel(
            name='Simulacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_imovel', models.DecimalField(decimal_places=2, max_digits=15)),
                ('entrada', models.DecimalField(decimal_places=2, max_digits=15)),
                ('taxa_anual', models.DecimalField(decimal_places=2, max_digits=5)),
                ('prazo_meses', models.IntegerField()),
                ('parcela_fixa', models.DecimalField(decimal_places=2, max_digits=15)),
                ('total_juros', models.DecimalField(decimal_places=2, max_digits=15)),
                ('data_simulacao', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='simulacao.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Financiamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_imovel', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Valor do Imóvel')),
                ('entrada', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Entrada (Recursos Próprios + FGTS)')),
                ('taxa_juros_anual', models.DecimalField(decimal_places=3, max_digits=5, verbose_name='Taxa de Juros Anual (%)')),
                ('prazo_meses', models.IntegerField(verbose_name='Prazo Total em Meses')),
                ('valor_despesas', models.DecimalField(decimal_places=2, default=0.0, max_digits=15, verbose_name='Total de Despesas de Transação')),
                ('incorporar_despesas', models.BooleanField(default=True, verbose_name='Incorporar Despesas no Financiamento?')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='simulacao.usuario')),
            ],
            options={
                'verbose_name': 'Financiamento',
                'verbose_name_plural': 'Financiamentos',
            },
        ),
        migrations.AddField(
            model_name='cenariocomparativo',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='simulacao.usuario'),
        ),
    ]
