# Generated by Django 5.2.8 on 2025-11-26 12:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulacao', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Financiamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_imovel', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Valor do Imóvel')),
                ('entrada', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Entrada (Recursos Próprios + FGTS)')),
                ('taxa_juros_anual', models.DecimalField(decimal_places=3, max_digits=5, verbose_name='Taxa de Juros Anual (%)')),
                ('prazo_meses', models.IntegerField(verbose_name='Prazo Total em Meses')),
                ('valor_despesas', models.DecimalField(decimal_places=2, default=0.0, max_digits=15, verbose_name='Total de Despesas de Transação (ITBI, Cartório, Avaliação, etc.)')),
                ('incorporar_despesas', models.BooleanField(default=True, verbose_name='Incorporar Despesas no Financiamento?')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='simulacao.usuario')),
            ],
            options={
                'verbose_name': 'Financiamento',
                'verbose_name_plural': 'Financiamentos',
            },
        ),
    ]
