# Generated by Django 5.2.8 on 2026-03-15 17:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulacao', '0002_subscriptionplan_datadeletionrequest_lead_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LinkAfiliado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('banco', 'Banco'), ('consorcio', 'Consorcio'), ('corretora', 'Corretora'), ('seguradora', 'Seguradora')], max_length=50)),
                ('url_afiliado', models.URLField()),
                ('codigo_afiliado', models.CharField(blank=True, max_length=50)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='afiliados/')),
                ('ativo', models.BooleanField(default=True)),
                ('comissao_percentual', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('descricao', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Link Afiliado',
                'verbose_name_plural': 'Links Afiliados',
            },
        ),
        migrations.CreateModel(
            name='CliqueAfiliado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('pagina_origem', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='simulacao.linkafiliado')),
            ],
            options={
                'verbose_name': 'Clique em Afiliado',
                'verbose_name_plural': 'Cliques em Afiliados',
            },
        ),
    ]
