# Generated by Django 5.2.8 on 2026-03-27 02:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulacao', '0003_linkafiliado_cliqueafiliado'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad_type', models.CharField(choices=[('banner', 'Banner'), ('interstitial', 'Interstitial'), ('rewarded', 'Rewarded')], max_length=20)),
                ('page', models.CharField(max_length=100)),
                ('viewed_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Visualização de Anúncio',
                'verbose_name_plural': 'Visualizações de Anúncios',
            },
        ),
        migrations.CreateModel(
            name='PerfilUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plano', models.CharField(choices=[('gratis', 'Grátis'), ('premium', 'Premium')], default='gratis', max_length=20)),
                ('premium_ativo', models.BooleanField(default=False)),
                ('premium_expira', models.DateTimeField(blank=True, null=True)),
                ('produto_premium', models.CharField(blank=True, max_length=50, null=True)),
                ('data_premium', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil_ficalc', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Perfil de Usuário',
                'verbose_name_plural': 'Perfis de Usuário',
            },
        ),
        migrations.CreateModel(
            name='Transacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('premium_ativacao', 'Premium - Ativação'), ('premium_renovacao', 'Premium - Renovação'), ('premium_cancelamento', 'Premium - Cancelamento'), ('google_play_purchase', 'Google Play Purchase'), ('app_store_purchase', 'App Store Purchase')], max_length=50)),
                ('produto', models.CharField(blank=True, max_length=50, null=True)),
                ('valor', models.CharField(blank=True, max_length=50, null=True)),
                ('status', models.CharField(choices=[('sucesso', 'Sucesso'), ('falha', 'Falha'), ('pendente', 'Pendente')], default='pendente', max_length=20)),
                ('id_transacao_externa', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('dados_adicionais', models.JSONField(blank=True, default=dict)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transacoes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Transação',
                'verbose_name_plural': 'Transações',
                'ordering': ['-data'],
            },
        ),
        migrations.CreateModel(
            name='UsoRecursos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=50)),
                ('contador', models.IntegerField(default=0)),
                ('limite_maximo', models.IntegerField()),
                ('ultimo_reset', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uso_recursos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Uso de Recurso',
                'verbose_name_plural': 'Uso de Recursos',
                'unique_together': {('usuario', 'tipo')},
            },
        ),
    ]
