# Generated by Django 6.0.1 on 2026-03-30 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulacao', '0004_adview_perfilusuario_transacao_usorecursos'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionplan',
            name='pdf_white_label',
            field=models.BooleanField(default=False, help_text='Permite ao corretor personalizar o PDF com logo e dados de contato', verbose_name='PDF White-Label para Corretores'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='creci',
            field=models.CharField(blank=True, help_text='Número de registro no CRECI (Conselho Regional de Corretores de Imóveis)', max_length=20, null=True, verbose_name='CRECI'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='logo_empresa',
            field=models.ImageField(blank=True, help_text='Logo que aparecerá no cabeçalho do PDF (recomendado: PNG transparente, max 500KB)', null=True, upload_to='logos_corretores/', verbose_name='Logo da Empresa'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='nome_empresa',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nome da Empresa/Imobiliária'),
        ),
    ]
