# Generated by Django 6.0.1 on 2026-04-12 17:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulacao', '0005_add_broker_profile_and_white_label_plan'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParametrosMercado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valorizacao_imovel_aa', models.DecimalField(decimal_places=2, default=5.0, max_digits=5, verbose_name='Valorização do Imóvel (% a.a.)')),
                ('inflacao_aa', models.DecimalField(decimal_places=2, default=4.5, max_digits=5, verbose_name='Inflação / IPCA (% a.a.)')),
                ('taxa_selic_aa', models.DecimalField(decimal_places=2, default=10.5, max_digits=5, verbose_name='Taxa SELIC/CDI (% a.a.)')),
                ('rendimento_poupanca_aa', models.DecimalField(decimal_places=2, default=6.17, max_digits=5, verbose_name='Rendimento Poupança (% a.a.)')),
                ('comprometimento_renda_max', models.IntegerField(default=30, verbose_name='Comprometimento de Renda Máximo (%)')),
                ('itbi_registro_percentual', models.DecimalField(decimal_places=2, default=4.0, max_digits=4, verbose_name='ITBI + Registro (%)')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='parametros', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WizardLead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome Completo')),
                ('whatsapp', models.CharField(max_length=25, verbose_name='WhatsApp')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-mail')),
                ('valor_imovel', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('perfil', models.CharField(blank=True, max_length=50, null=True)),
                ('cidade', models.CharField(blank=True, max_length=100, null=True)),
                ('origem', models.CharField(choices=[('WEB', 'Web'), ('MOBILE', 'Mobile')], default='WEB', max_length=20)),
                ('consentimento_lgpd', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('simulacao_vinculada', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='simulacao.savedsimulation')),
            ],
            options={
                'verbose_name': 'Lead do Wizard',
                'verbose_name_plural': 'Leads do Wizard',
                'ordering': ['-criado_em'],
            },
        ),
    ]
